package com.mrh0.createatomic.config;

import net.createmod.catnip.config.ConfigBase;

public class CAtomicServer extends ConfigBase {

    public final ConfigGroup reactor = group(0, "reactor", "Reactor settings");

    public final ConfigInt fuelRodDuration = i(72000 * 2, 1, Integer.MAX_VALUE, "fuelRodDuration",
            "How many ticks a uranium fuel rod lasts before becoming depleted.",
            "72000 = 60 minutes at 20 TPS.");

    public final ConfigInt plutoniumFuelRodDuration = i(72000 * 2 * 3, 1, Integer.MAX_VALUE, "plutoniumFuelRodDuration",
            "How many ticks a plutonium fuel rod lasts before becoming depleted.",
            "Default is 3x the uranium fuel rod duration.");

    public final ConfigBool meltdownEnabled = b(true, "meltdownEnabled",
            "Whether reactors can melt down. When false, a reactor at 0% hull integrity",
            "shuts down instead of exploding, and slowly self-repairs when cooled.");

    public final ConfigBool meltdownExplosion = b(true, "meltdownExplosion",
            "Whether a reactor meltdown triggers an explosion.");

    public final ConfigBool blockRadiationEnabled = b(true, "blockRadiationEnabled",
            "Whether reactor debris and reactors emits radiation sickness effects to nearby entities.");

    public final ConfigBool radiationEffectEnabled = b(true, "radiationEffectEnabled",
            "Whether the Radioactivity mob effect can be applied to entities at all.",
            "When false, all sources of radiation have no effect.");

    public final ConfigFloat turbineCapacity = f(16.0f, 0.1f, 1024f, "turbineCapacity",
            "Stress capacity (SU per RPM) generated by each Steam Turbine.");

    public final ConfigFloat hullRegenRate = f(0.5f, 0f, 100f, "hullRegenRate",
            "Hull integrity regenerated per lazy tick (every ~1 s) when the reactor is fully cooled.",
            "0.5 = full regen from 0% in ~160 seconds.");

    public final ConfigFloat rhgDecayDays = f(2f, 0.01f, 3650.0f, "rhgDecayDays",
            "Average real-world days (24 hours at 20 TPS) between each decay step of the Radioisotope Heat Generator.",
            "Each step: heated -> smouldering -> inert.",
            "1.0 = on average (random) 24 real hours (~1,728,000 ticks) per step.");

    public final ConfigGroup rtg = group(0, "rtg", "Radioisotope Thermoelectric Generator settings");

    public final ConfigInt rtgEnergyPerTick = i(10, 1, Integer.MAX_VALUE, "rtgEnergyPerTick",
            "Forge Energy (FE) generated per tick by each RTG block.");

    public final ConfigInt rtgBufferCapacity = i(16_000, 1, Integer.MAX_VALUE, "rtgBufferCapacity",
            "Maximum FE stored in the RTG's internal buffer.");

    public final ConfigInt rtgRadiationRadius = i(4, 1, 64, "rtgRadiationRadius",
            "Radius in blocks at which each RTG block applies the Radioactivity effect.");

    @Override
    public String getName() {
        return "server";
    }
}
